<?php

require_once dirname(__FILE__) . '/../../trunk/class_vcard_storage.php';

/**
 * Test class for class_vcard_storage.
 * Generated by PHPUnit on 2010-11-22 at 02:36:42.
 */
class class_vcard_storageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var class_vcard_storage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new class_vcard_storage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     *  Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestSkipped();
    }

    /**
     * @todo Implement testIs_alive().
     */
    public function testIs_alive() {
        // Remove the following lines when you implement this test.
        if ($this->object instanceof class_vcard_storage) {
            $this->assertTrue($this->object->is_alive());
        }
    }

    /**
     * @todo Implement testGet_vCard_Explanatory_Properties().
     */
//    public function testGet_vCard_Explanatory_Properties() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vCard_Identification_Properties().
     */
//    public function testGet_vCard_Identification_Properties() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vCard_Telecommunications_Addressing_Properties_Tel().
     */
//    public function testGet_vCard_Telecommunications_Addressing_Properties_Tel() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vCard_Telecommunications_Addressing_Properties_Email().
     */
//    public function testGet_vCard_Telecommunications_Addressing_Properties_Email() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vCard_Delivvery_Addressing_Properties_LABEL().
     */
//    public function testGet_vCard_Delivvery_Addressing_Properties_LABEL() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vCard_Delivvery_Addressing_Properties_ADR().
     */
//    public function testGet_vCard_Delivvery_Addressing_Properties_ADR() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vCard_Organizational_Properties().
     */
//    public function testGet_vCard_Organizational_Properties() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vCard_Geographical_Properties().
     */
//    public function testGet_vCard_Geographical_Properties() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testGet_vcard_id_by_uid().
     */
//    public function testGet_vcard_id_by_uid() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @todo Implement testStore_data().
     */
    public function testStore_data() {
        // Remove the following lines when you implement this test.
        $vcard_explanatory_properties = array(
            'UID' => '53b1f1c4-e695-11df-97aa-000c294ea793',
            'REV' => '20101013111111',
            'VERSION' => 3.0,
            'LANGAGE' => '',
            'CATEGORIES' => '',
            'PRODID' => '',
            'SORT-STRING' => ''
        );
        $r_array = $this->object->store_data('vCard_Explanatory_Properties', $vcard_explanatory_properties);
        print_r($r_array);
    }

    /**
     * @todo Implement testCheckExistVcardRecordByUid().
     */
    public function testCheckExistVcardRecordByUid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
